superhero_database/superhero_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_database/superheroes/urls.py
from django.urls import path
from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('/', views.update_superhero, name='update_superhero'),
    path('/', views.delete_superhero, name='delete_superhero')
]

superhero_database/superheroes/models.py
from django.db import models

# Create your models here.


class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_superhero_ability = models.CharField(max_length=50)
    secondary_superhero_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=100)

    def __str__(self):
        return self.name

superhero_database/superheroes/views.py
from django.shortcuts import render
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def detail(request, superhero_id):
    temp_hero = Superhero.objects.get(pk=superhero_id)
    context = {'superhero': temp_hero}
    return render(request, 'superheroes/detail.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superpower = request.POST.get('primary_superpower')
        secondary_superpower = request.POST.get('secondary_superpower')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_superhero_ability=primary_superpower, secondary_superhero_ability=secondary_superpower, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')


def update_superhero(request):
    if request.method == 'POST':
        idn = request.POST.get('id')
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superpower = request.POST.get('primary_superpower')
        secondary_superpower = request.POST.get('secondary_superpower')
        catchphrase = request.POST.get('catchphrase')
        updated_hero = Superhero(id=idn, name=name, alter_ego=alter_ego, primary_superhero_ability=primary_superpower, secondary_superhero_ability=secondary_superpower, catchphrase=catchphrase)
        updated_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))


def delete_superhero(request):
    exiled_hero = Superhero.objects.get(pk=superhero_id)
    return request, exiled_hero.delete()

superhero_database/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{superhero.name}}</title>
</head>
<body>
<h1>Name:  {{superhero.name}}</h1>
<h2>Alter Ego:  {{superhero.alter_ego}}</h2>
<p>Primary Superpower: {{superhero.primary_superhero_ability}}<br></p>
<p>Secondary Superpower: {{superhero.secondary_superhero_ability}}<br></p>
<p>Catchphrase:  {{superhero.catchphrase}}</p>

<form action="{% url 'superheroes:update_superhero' %}" method="post">
    {% csrf_token %}
   <p>Please Re-enter all the information so that it can be updated.</p>
    ID[DO NOT CHANGE!]:<input type="text" name="id" value={{superhero.id}}><br>
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Superpower:<input type="text" name="primary_superpower" id="primary_superpower"><br>
    Secondary Superpower:<input type="text" name="secondary_superpower" id="secondary_superpower"><br>
    Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
    <input type="submit" value="Update Hero">
</form>
<form action="{% url 'superheroes:delete_superhero' %}" method=post>
    {% csrf_token %}
    <input type="submit" value="Delete Superhero">
</form>
</body>
</html>

superhero_database/superheroes/templates/superheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superheroes Index</title>
</head>
<body>
<h1>This is going to be a super website :$</h1>
<ul>
  {% for superhero in all_superheroes %}
    <li>
        <h2>{{superhero.name}}</h2>
        <a href="{% url 'superheroes:detail' superhero.id %}">See more info</a>
    </li>
  {% endfor %}
</ul>



<form action="{% url 'superheroes:create_new_superhero' %}" method="post">
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Superpower:<input type="text" name="primary_superpower" id="primary_superpower"><br>
    Secondary Superpower:<input type="text" name="secondary_superpower" id="secondary_superpower"><br>
    Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
    <input type="submit" value="Add New Superhero!">
</form>

</body>
</html>